
# Flutter build

trigger:
- main

jobs:
  - job: Android
    pool:
      vmImage: 'macOS-latest'

- task: FlutterInstall@0
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'latest'

- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: '.'

